version: '3.8'

services:
  # MongoDB 설정
  mongo:
    image: mongo:6.0
    container_name: cloudbridge-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=cloudbridge
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - cloudbridge-network

  # PostgreSQL 설정
  postgres:
    image: postgres:15
    container_name: cloudbridge-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cloudbridge
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=cloudbridge
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - cloudbridge-network

  # Redis 설정
  redis:
    image: redis:7
    container_name: cloudbridge-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - cloudbridge-network

  # Kafka 및 Zookeeper 설정
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: cloudbridge-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - cloudbridge-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: cloudbridge-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - cloudbridge-network

  # ClickHouse 설정
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: cloudbridge-clickhouse
    ports:
      - "8123:8123"  # HTTP 인터페이스
      - "9000:9000"  # 네이티브 인터페이스
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    restart: always
    networks:
      - cloudbridge-network

  # Grafana 설정
  grafana:
    image: grafana/grafana:latest
    container_name: cloudbridge-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    networks:
      - cloudbridge-network

  # Loki 설정
  loki:
    image: grafana/loki:latest
    container_name: cloudbridge-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
    networks:
      - cloudbridge-network

  # Prometheus 설정
  prometheus:
    image: prom/prometheus:latest
    container_name: cloudbridge-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: always
    networks:
      - cloudbridge-network

volumes:
  mongo_data:
  postgres_data:
  redis_data:
  clickhouse_data:
  grafana_data:
  prometheus_data:

networks:
  cloudbridge-network:
    driver: bridge 