replicaCount: 1

image:
  repository: platform-menu-fe
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4200

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: menu.autoriseinsight.co.kr
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: menu-tls
      hosts:
        - menu.autoriseinsight.co.kr

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {} 