default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight"
  lane :deploy_tf do
    # 인증서 및 프로비저닝 프로파일 동기화
    match(
      type: "appstore",
      readonly: true
    )
    
    # 빌드 버전 자동 증가
    increment_build_number(
      build_number: latest_testflight_build_number + 1
    )
    
    # 앱 빌드
    gym(
      scheme: "App",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.autorise.cloudbridge" => "match AppStore com.autorise.cloudbridge"
        }
      }
    )
    
    # TestFlight 업로드
    pilot(
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false
    )
  end
end 