apiVersion: v1
kind: Service
metadata:
  name: platform-menu
  labels:
    app: platform-menu
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: platform-menu
    release: {{ .Release.Name }} 