theme:
  colors:
    primary:
      main: '#2563EB'
  typography:
    fontFamily: 'Pretendard, -apple-system, BlinkMacSystemFont, system-ui, Roboto, sans-serif'
    fontSize: '16px'
    headings:
      fontFamily: 'Pretendard, -apple-system, BlinkMacSystemFont, system-ui, Roboto, sans-serif'
      fontWeight: 600

logo:
  url: 'https://autoriseinsight.co.kr/logo.png'
  altText: 'CloudBridge Logo'
  backgroundColor: '#FFFFFF'

downloadUrl: '/openapi.yaml'
downloadFileName: 'cloudbridge-openapi.yaml'

hideDownloadButton: false
hideLoading: true
expandResponses: "200,201"
requiredPropsFirst: true
sortPropsAlphabetically: false
showExtensions: true

unstable_externalDescription: |
  # CloudBridge Platform API 문서
  
  이 문서는 CloudBridge Platform의 API 명세를 제공합니다.
  
  ## 인증
  모든 API는 OAuth2.0 인증이 필요합니다. 자세한 내용은 [인증 가이드](https://docs.autoriseinsight.co.kr/auth)를 참고하세요.
  
  ## 버전 관리
  API는 시맨틱 버저닝을 따릅니다. 주요 변경사항은 메이저 버전으로 관리됩니다.
  
  ## 지원
  기술 지원이 필요한 경우 support@autoriseinsight.co.kr로 문의해주세요. 