default_platform(:android)

platform :android do
  desc "Deploy to Play Store Internal Testing"
  lane :deploy_play do
    # 릴리스 빌드 생성
    gradle(
      task: "clean bundleRelease",
      properties: {
        "android.injected.signing.store.file" => ENV["KEYSTORE_FILE"],
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEY_PASSWORD"],
      }
    )
    
    # Play Store 업로드
    upload_to_play_store(
      track: 'internal',
      aab: './app/build/outputs/bundle/release/app-release.aab',
      json_key: './fastlane/service-account.json',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end 